variables:
  BUILD_HELPERS_VERSION: b67f7745a1485878063a43c3d5dc8b21eb15e966

image: node:20

stages:
  - build

build:
  stage: build
  interruptible: true
  before_script:
    - git init build-helpers -q -b unused
    - git -C build-helpers fetch -q --depth 1 $CI_SERVER_PROTOCOL://gitlab-ci-token:${CI_JOB_TOKEN}@$CI_SERVER_HOST:$CI_SERVER_PORT/linbit/build-helpers.git $BUILD_HELPERS_VERSION
    - git -C build-helpers checkout -q $BUILD_HELPERS_VERSION
    - . build-helpers/gitlab-utils.sh
    - ci_prepare_tools
    - ci_fetch_lbbuildctl
  script:
    - echo "Node.js version:"
    - node -v
    - echo "npm version:"
    - npm -v
    - VERSION="0.0.0.$CI_COMMIT_SHORT_SHA"
    - install /dev/null /usr/local/bin/lbvers.py # disable version checking
    - build-helpers/dummy-release.sh linstor-gui $VERSION 1 linstor-gui.spec
    - make VERSION="$VERSION" debrelease
    - curl -isSf -u $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD
          --upload-file linstor-gui-*.tar.gz
          $LINBIT_REGISTRY_URL/repository/lbbuild-upstream/
    - lbbuildctl build linstor-gui --ci -v "$VERSION"
          -e LINBIT_REGISTRY_USER=$LINBIT_REGISTRY_USER
          -e LINBIT_REGISTRY_PASSWORD=$LINBIT_REGISTRY_PASSWORD
          -e LINBIT_REGISTRY_URL=$LINBIT_REGISTRY_URL
          --arch amd64
          -d ubuntu-noble -d rhel9.0

  artifacts:
    paths:
      - 'linstor-gui-*.tar.gz'
    expire_in: '30 days'

sbom:
  rules:
    - if: $CI_COMMIT_TAG
  stage: build
  before_script:
    - git init build-helpers -q -b unused
    - git -C build-helpers fetch -q --depth 1 $CI_SERVER_PROTOCOL://gitlab-ci-token:${CI_JOB_TOKEN}@$CI_SERVER_HOST:$CI_SERVER_PORT/linbit/build-helpers.git $BUILD_HELPERS_VERSION
    - git -C build-helpers checkout -q $BUILD_HELPERS_VERSION
    - . build-helpers/gitlab-utils.sh
    - ci_prepare_tools
  script:
    - make sbom
    - ci_put_bom linstor-gui $CI_COMMIT_TAG sbom/linstor-gui.cdx.json
