// SPDX-License-Identifier: GPL-3.0
//
// Copyright (c) 2024 LINBIT
//
// Author: Liang Li <liang.li@linbit.com>

import { describe, expect, it } from 'vitest';

// @ts-expect-error -- plain JS generator, no types
import { extractMetaXml, scrubUrl } from '../../../../../scripts/generate-windows-agents.mjs';
import { windowsAgents } from '../windows_agents';

// windows_agents.ts is generated by scripts/generate-windows-agents.mjs from a
// clone of ocf-resource-agents-rust, so unlike the old committed-JSON setup
// there is no source to diff against here. Two things are checked instead: the
// parsing the generator does (pure functions, no clone), and that the committed
// catalog still looks like a catalog.

const generated = windowsAgents.providers.linbit;

describe('extractMetaXml', () => {
  it('pulls the meta-data out of a raw string literal', () => {
    const source = `
      fn meta_data(&self) -> Result<OcfStatus, OcfError> {
          println!(r#"<?xml version="1.0"?>
      <resource-agent name="ipaddr2-windows" version="1.0">
      </resource-agent>
      "#);
      }`;
    expect(extractMetaXml(source)).toContain('<resource-agent name="ipaddr2-windows"');
  });

  it('skips raw strings that are not meta-data', () => {
    const source = 'let msg = r#"not metadata"#; let x = r#"<resource-agent name="a"/>"#;';
    expect(extractMetaXml(source)).toBe('<resource-agent name="a"/>');
  });

  it('respects the hash count, so a quote inside the XML does not end it early', () => {
    // `"#` is legal inside an r##"..."## literal; matching on `"#` alone would
    // truncate the document and silently drop every parameter after it.
    const source = 'r##"<resource-agent name="a"><longdesc>see "#1</longdesc></resource-agent>"##';
    expect(extractMetaXml(source)).toContain('</resource-agent>');
  });

  it('returns null when a file carries no agent', () => {
    expect(extractMetaXml('fn main() { println!("hello"); }')).toBeNull();
  });
});

describe('scrubUrl', () => {
  it('strips the CI job token, which would otherwise land in the committed file', () => {
    expect(scrubUrl('https://gitlab-ci-token:s3cret@gitlab.example.com/drbd/x.git')).toBe(
      'https://gitlab.example.com/drbd/x.git',
    );
  });

  it('leaves a plain URL and an scp-style remote alone', () => {
    expect(scrubUrl('https://gitlab.example.com/drbd/x.git')).toBe('https://gitlab.example.com/drbd/x.git');
    expect(scrubUrl('git@gitlab.example.com:drbd/x.git')).toBe('git@gitlab.example.com:drbd/x.git');
  });
});

describe('windows_agents.ts', () => {
  it('covers the WinDRBD agent set', () => {
    expect(generated.map((agent) => agent.name).sort()).toEqual([
      'DRBD',
      'Filesystem',
      'HyperV',
      'guard',
      'ipaddr2-windows',
      'mssql_server_attach_database',
      'windows_service',
      'windows_share',
    ]);
  });

  it('gives every agent a name and at least one action', () => {
    for (const agent of generated) {
      expect(agent.name).toBeTruthy();
      expect(agent.actions.length).toBeGreaterThan(0);
    }
  });

  it('keeps the actions only Windows agents have', () => {
    // migrate_to / node-lost drive live migration and crash failover; the
    // hand-written catalog that preceded the generator dropped every action.
    const hyperV = generated.find((agent) => agent.name === 'HyperV');
    expect(hyperV?.actions.map((a) => a.name)).toEqual(expect.arrayContaining(['start', 'stop', 'node-lost']));
  });

  it('carries unique and default, which the repo JSON conversion drops', () => {
    // Reading the meta-data XML rather than ocf2json.py output is the whole
    // reason these exist here; losing them again should fail loudly.
    const params = generated.flatMap((agent) => agent.parameters);
    expect(params.length).toBeGreaterThan(0);
    for (const param of params) {
      expect(param).toHaveProperty('unique');
      expect(param).toHaveProperty('default');
    }
  });

  it('is sorted by name, so a regeneration produces a reviewable diff', () => {
    const names = generated.map((agent) => agent.name);
    expect(names).toEqual([...names].sort((a, b) => a.localeCompare(b)));
  });
});
