// SPDX-License-Identifier: GPL-3.0
//
// Copyright (c) 2024 LINBIT
//
// Author: Liang Li <liang.li@linbit.com>

/**
 * Generates the "make the LINSTOR controller highly available" Python script
 * shown on the last step of the cluster-setup wizard. The script mirrors the
 * LINSTOR user guide §3.1 and is deliberately self-contained: everything it
 * needs (node names, replica count, controller IPs — and, on single-pool
 * clusters, even the storage pool) is discovered from the live cluster at
 * runtime. The wizard only prefills the STORAGE_POOL constant as a
 * convenience; an empty value means auto-detect.
 */

export interface HaSetupScriptOptions {
  /** Storage pool backing the controller-DB resource (prefill only; the script auto-detects on single-pool clusters). */
  storagePool?: string;
}

export const buildHaSetupScript = ({ storagePool }: HaSetupScriptOptions = {}): string => {
  const pool = storagePool?.trim() || '';

  return `#!/usr/bin/env python3
"""Make the LINSTOR controller highly available (DRBD Reactor promoter).

Generated by LINSTOR GUI — mirrors the LINSTOR user guide section
"Creating a highly available LINSTOR cluster".

Run this script AS ROOT on the node that is CURRENTLY running
linstor-controller. It will:

  1. create a dedicated DRBD resource (${'`'}linstor_db${'`'}) for the controller DB
  2. move /var/lib/linstor onto that resource
  3. hand controller start/stop over to drbd-reactor (promoter)
  4. print the exact commands to run on every standby controller node

Requirements on this node: linstor CLI (talking to this controller),
drbd-utils, drbd-reactor. Standby nodes need linstor-controller and
drbd-reactor installed as well.
"""

import json
import os
import shutil
import socket
import subprocess
import sys
import time

# ---- parameters --------------------------------------------------------
# Node names, replica count and controller IPs are discovered from the
# live cluster at runtime. STORAGE_POOL may be left empty: on a cluster
# with a single storage pool it is auto-detected; with several pools, set
# it here.
RESOURCE = "linstor_db"
RESOURCE_GROUP = "linstor-db-grp"
STORAGE_POOL = ${JSON.stringify(pool)}
DB_SIZE = "200M"

MOUNT_UNIT_PATH = "/etc/systemd/system/var-lib-linstor.mount"
REACTOR_CONF_PATH = "/etc/drbd-reactor.d/linstor_db.toml"
SATELLITE_DROPIN_DIR = "/etc/systemd/system/linstor-satellite.service.d"
SATELLITE_DROPIN_PATH = SATELLITE_DROPIN_DIR + "/ha.conf"
CLIENT_CONF_PATH = "/etc/linstor/linstor-client.conf"

MOUNT_UNIT = """[Unit]
Description=Filesystem for the LINSTOR controller

[Mount]
What=/dev/drbd/by-res/linstor_db/0
Where=/var/lib/linstor
"""

REACTOR_CONF = """[[promoter]]
[promoter.resources.linstor_db]
start = ["var-lib-linstor.mount", "linstor-controller.service"]
"""

SATELLITE_DROPIN = """[Service]
Environment=LS_KEEP_RES=linstor_db
"""

# drbd-reactor "Automatic Reload" units (from the package example dir): reload
# the daemon whenever a config snippet under /etc/drbd-reactor.d changes, so
# activating the promoter never depends on a fragile restart.
RELOAD_PATH_UNIT = """[Unit]
Description=Reload drbd-reactor on plugin changes

[Path]
PathChanged=/etc/drbd-reactor.d
TriggerLimitIntervalSec=0

[Install]
WantedBy=multi-user.target
"""

RELOAD_SERVICE_UNIT = """[Unit]
Description=Reload drbd-reactor on plugin changes
After=drbd-reactor.service
StartLimitIntervalSec=0

[Service]
Type=oneshot
ExecStart=/usr/bin/systemctl reload drbd-reactor.service

[Install]
WantedBy=multi-user.target
"""

REACTOR_EXAMPLE_DIR = "/usr/share/doc/drbd-reactor/examples"


def run(cmd, check=True, capture=False):
    print("+ " + " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=check, text=True,
                          capture_output=capture)


def out(cmd):
    return subprocess.run(cmd, check=True, text=True,
                          capture_output=True).stdout


def die(msg):
    print("ERROR: " + msg, file=sys.stderr)
    sys.exit(1)


def confirm(prompt):
    reply = input(prompt + " [y/N] ").strip().lower()
    if reply != "y":
        die("aborted by user")


def write_file(path, content):
    print("+ write " + path, flush=True)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)


def preflight():
    if os.geteuid() != 0:
        die("run this script as root")
    for tool in ("linstor", "drbdadm", "drbd-reactor", "mkfs.ext4"):
        if shutil.which(tool) is None:
            die(tool + " not found in PATH — install it first from your "
                "LINBIT repository (or ppa:linbit/linbit-drbd9-stack on "
                "Ubuntu); this script deliberately does not install packages")
    state = subprocess.run(["systemctl", "is-active", "--quiet",
                            "linstor-controller"]).returncode
    if state != 0:
        die("linstor-controller is not active on this node — run the "
            "script on the node currently running the controller")
    # The controller must be reachable before we start moving its DB.
    run(["linstor", "node", "list"], capture=True)
    resources = json.loads(out(["linstor", "--machine-readable",
                                "resource", "list", "-r", RESOURCE]))
    if resources and resources[0]:
        die("resource '" + RESOURCE + "' already exists — this cluster "
            "looks already (partially) HA-configured; resolve manually")
    if os.path.exists(MOUNT_UNIT_PATH):
        die(MOUNT_UNIT_PATH + " already exists — resolve manually")
    # The controller node must itself be a registered cluster node (running
    # linstor-satellite) — otherwise the DB resource can never be brought up
    # locally and the migration would strand halfway.
    me = socket.gethostname().split(".")[0]
    if me not in cluster_node_names():
        die("this node ('" + me + "') is not registered in the LINSTOR "
            "cluster — install/start linstor-satellite here and register "
            "it (nodes: " + (", ".join(cluster_node_names()) or "none")
            + ")")


def resolve_storage_pool():
    data = json.loads(out(["linstor", "--machine-readable",
                           "storage-pool", "list"]))
    pools = sorted({sp.get("storage_pool_name", "")
                    for sp in (data[0] if data else [])
                    if sp.get("storage_pool_name")
                    and sp.get("provider_kind") != "DISKLESS"})
    if STORAGE_POOL:
        if STORAGE_POOL not in pools:
            die("storage pool '" + STORAGE_POOL + "' not found on this "
                "cluster — available: " + (", ".join(pools) or "none"))
        return STORAGE_POOL
    if len(pools) == 1:
        return pools[0]
    die("cannot auto-detect the storage pool (found: "
        + (", ".join(pools) or "none")
        + ") — set STORAGE_POOL at the top of this script")


def cluster_node_names():
    nodes = json.loads(out(["linstor", "--machine-readable", "node", "list"]))
    return [n.get("name", "") for n in (nodes[0] if nodes else [])
            if n.get("name")]


def db_place_count():
    """3 replicas when the cluster has them; 2 on a two-node cluster."""
    count = len(cluster_node_names())
    if count < 2:
        die("controller HA needs at least 2 nodes; this cluster has "
            + str(count))
    if count == 2:
        print("WARNING: 2-node cluster — no real quorum; consider adding "
              "a third (diskless) node")
    return 3 if count >= 3 else 2


def rg_exists():
    groups = json.loads(out(["linstor", "--machine-readable",
                             "resource-group", "list"]))
    names = [g.get("name", "") for g in (groups[0] if groups else [])]
    return RESOURCE_GROUP in names


def create_db_resource(pool):
    if rg_exists():
        print("resource group " + RESOURCE_GROUP + " already exists, reusing")
    else:
        run(["linstor", "resource-group", "create",
             "--storage-pool", pool,
             "--place-count", str(db_place_count()),
             "--diskless-on-remaining", "true",
             RESOURCE_GROUP])
        run(["linstor", "volume-group", "create", RESOURCE_GROUP])
    run(["linstor", "resource-group", "drbd-options",
         "--auto-promote=no",
         "--quorum=majority",
         "--on-suspended-primary-outdated=force-secondary",
         "--on-no-quorum=io-error",
         "--on-no-data-accessible=io-error",
         RESOURCE_GROUP])
    run(["linstor", "resource-group", "spawn-resources",
         RESOURCE_GROUP, RESOURCE, DB_SIZE])


def wait_for_device(path, timeout=60):
    for _ in range(timeout):
        if os.path.exists(path):
            return
        time.sleep(1)
    die(path + " did not appear within " + str(timeout) + "s")


def move_db():
    wait_for_device("/dev/drbd/by-res/linstor_db/0")
    run(["systemctl", "disable", "--now", "linstor-controller"])
    write_file(MOUNT_UNIT_PATH, MOUNT_UNIT)
    run(["systemctl", "daemon-reload"])
    if os.path.exists("/var/lib/linstor.orig"):
        die("/var/lib/linstor.orig already exists — resolve manually")
    os.rename("/var/lib/linstor", "/var/lib/linstor.orig")
    os.mkdir("/var/lib/linstor")
    run(["drbdadm", "primary", RESOURCE])
    run(["mkfs.ext4", "-b", "4096", "/dev/drbd/by-res/linstor_db/0"])
    run(["systemctl", "start", "var-lib-linstor.mount"])
    run(["cp", "-a", "/var/lib/linstor.orig/.", "/var/lib/linstor/"])


def client_conf_text():
    """linstor-client config listing every controller candidate, so the
    linstor CLI keeps working on all nodes after a failover."""
    nodes = json.loads(out(["linstor", "--machine-readable", "node", "list"]))
    ips = []
    for n in (nodes[0] if nodes else []):
        for ni in n.get("net_interfaces", []):
            if ni.get("address"):
                ips.append(ni["address"])
                break
    if not ips:
        ips = ["localhost"]
    return "[global]\\ncontrollers=" + ",".join(ips) + "\\n"


def install_reactor_reload():
    """Install + enable the drbd-reactor auto-reload path unit (drbd-reactor
    docs: "Automatic Reload") so the daemon reloads whenever a snippet under
    /etc/drbd-reactor.d changes. Copies the packaged example units when
    present, otherwise writes them inline."""
    for unit, content in (("drbd-reactor-reload.path", RELOAD_PATH_UNIT),
                          ("drbd-reactor-reload.service", RELOAD_SERVICE_UNIT)):
        example = os.path.join(REACTOR_EXAMPLE_DIR, unit)
        dst = "/etc/systemd/system/" + unit
        if os.path.exists(example):
            shutil.copy(example, dst)
        else:
            write_file(dst, content)
    run(["systemctl", "daemon-reload"])
    run(["systemctl", "enable", "--now", "drbd-reactor-reload.path"])


def controller_active():
    return subprocess.run(["systemctl", "is-active", "--quiet",
                           "linstor-controller"]).returncode == 0


def wait_controller(timeout_steps=30):
    for _ in range(timeout_steps):
        if controller_active():
            return True
        time.sleep(2)
    return False


def hand_off_to_reactor():
    write_file(SATELLITE_DROPIN_PATH, SATELLITE_DROPIN)
    write_file(CLIENT_CONF_PATH, client_conf_text())
    run(["systemctl", "daemon-reload"])
    run(["systemctl", "enable", "--now", "drbd-reactor"])
    install_reactor_reload()
    run(["systemctl", "restart", "linstor-satellite"])
    # Write the promoter snippet last: the reload path unit watches
    # /etc/drbd-reactor.d and reloads drbd-reactor when it appears, activating
    # the promoter without a restart. Reload again explicitly (harmless if the
    # path unit already did) so we do not depend on path-unit timing.
    write_file(REACTOR_CONF_PATH, REACTOR_CONF)
    run(["systemctl", "reload", "drbd-reactor"], check=False)
    if not wait_controller():
        # last resort if the reload did not take
        run(["systemctl", "stop", "drbd-reactor"])
        run(["systemctl", "start", "drbd-reactor"])
        if not wait_controller():
            die("linstor-controller did not come back under drbd-reactor — "
                "check 'drbd-reactorctl status " + RESOURCE + "' and "
                "'journalctl -u drbd-reactor'")
    run(["drbd-reactorctl", "status", RESOURCE], check=False)


def print_standby_instructions():
    me = socket.gethostname().split(".")[0]
    standby = [n for n in cluster_node_names() if n and n != me]
    if not standby:
        standby = ["<standby-node>"]
    print()
    print("=" * 72)
    print("DONE on this node. Now run the following ON EACH STANDBY NODE")
    print("(" + ", ".join(standby) + ") to finish the HA setup:")
    print("=" * 72)
    print("""
# --- sanity checks: required packages must be installed on this node ---
# (install from your LINBIT repository / PPA first; nothing is auto-installed)
command -v drbd-reactor >/dev/null || { echo 'ERROR: drbd-reactor is not installed'; exit 1; }
systemctl cat linstor-controller.service >/dev/null 2>&1 || { echo 'ERROR: linstor-controller is not installed'; exit 1; }
systemctl cat linstor-satellite.service >/dev/null 2>&1 || { echo 'ERROR: linstor-satellite is not installed'; exit 1; }

systemctl disable --now linstor-controller

cat <<'EOF' > /etc/systemd/system/var-lib-linstor.mount
""" + MOUNT_UNIT + """EOF

mkdir -p /var/lib/linstor

mkdir -p """ + SATELLITE_DROPIN_DIR + """
cat <<'EOF' > """ + SATELLITE_DROPIN_PATH + """
""" + SATELLITE_DROPIN + """EOF

cat <<'EOF' > """ + REACTOR_CONF_PATH + """
""" + REACTOR_CONF + """EOF

mkdir -p /etc/linstor
cat <<'EOF' > """ + CLIENT_CONF_PATH + """
""" + client_conf_text() + """EOF

# Install the drbd-reactor auto-reload path unit (reloads the daemon when a
# config snippet changes — avoids a fragile restart).
if [ -f """ + REACTOR_EXAMPLE_DIR + """/drbd-reactor-reload.path ]; then
  cp """ + REACTOR_EXAMPLE_DIR + """/drbd-reactor-reload.{path,service} /etc/systemd/system/
else
cat <<'EOF' > /etc/systemd/system/drbd-reactor-reload.path
""" + RELOAD_PATH_UNIT + """EOF
cat <<'EOF' > /etc/systemd/system/drbd-reactor-reload.service
""" + RELOAD_SERVICE_UNIT + """EOF
fi

systemctl daemon-reload
systemctl restart linstor-satellite
systemctl enable --now drbd-reactor drbd-reactor-reload.path
systemctl reload drbd-reactor
drbd-reactorctl status """ + RESOURCE + """
""")
    print("Integrations (Proxmox, CSI, ...) should also be pointed at the")
    print("list of all controller IPs. Once you have verified failover,")
    print("/var/lib/linstor.orig on this node can be removed.")


def main():
    preflight()
    pool = resolve_storage_pool()
    print("This will move the LINSTOR controller database onto a DRBD")
    print("resource ('" + RESOURCE + "', pool '" + pool + "', "
          + str(db_place_count()) + " replicas) and hand the controller "
          "over to drbd-reactor.")
    confirm("Continue?")
    create_db_resource(pool)
    move_db()
    hand_off_to_reactor()
    print_standby_instructions()


if __name__ == "__main__":
    main()
`;
};
