// SPDX-License-Identifier: GPL-3.0
//
// Copyright (c) 2024 LINBIT
//
// Author: Liang Li <liang.li@linbit.com>

/**
 * Generates the "make the LINSTOR controller highly available" Python script
 * shown on the last step of the cluster-setup wizard. The script mirrors the
 * LINSTOR user guide §3.1 and is parameterized with what the wizard already
 * knows (storage-pool name, node names) so the user can paste it into a root
 * shell on the active controller node and run it as-is.
 */

export interface HaSetupScriptOptions {
  /** Storage pool backing the controller-DB resource. */
  storagePool?: string;
  /** All cluster node names; the script excludes the local hostname itself. */
  nodeNames?: string[];
}

const DEFAULT_POOL = 'my-thin-pool';

export const buildHaSetupScript = ({ storagePool, nodeNames }: HaSetupScriptOptions = {}): string => {
  const pool = storagePool?.trim() || DEFAULT_POOL;
  const nodes = (nodeNames ?? []).map((n) => n.trim()).filter(Boolean);
  const placeCount = nodes.length >= 3 ? 3 : nodes.length === 2 ? 2 : 3;
  const nodesLiteral = JSON.stringify(nodes);

  return `#!/usr/bin/env python3
"""Make the LINSTOR controller highly available (DRBD Reactor promoter).

Generated by LINSTOR GUI — mirrors the LINSTOR user guide section
"Creating a highly available LINSTOR cluster".

Run this script AS ROOT on the node that is CURRENTLY running
linstor-controller. It will:

  1. create a dedicated DRBD resource (${'`'}linstor_db${'`'}) for the controller DB
  2. move /var/lib/linstor onto that resource
  3. hand controller start/stop over to drbd-reactor (promoter)
  4. print the exact commands to run on every standby controller node

Requirements on this node: linstor CLI (talking to this controller),
drbd-utils, drbd-reactor. Standby nodes need linstor-controller and
drbd-reactor installed as well.
"""

import json
import os
import shutil
import socket
import subprocess
import sys
import time

# ---- parameters (from the LINSTOR GUI cluster-setup wizard) ----------------
RESOURCE = "linstor_db"
RESOURCE_GROUP = "linstor-db-grp"
STORAGE_POOL = ${JSON.stringify(pool)}
PLACE_COUNT = ${placeCount}
DB_SIZE = "200M"
# Every node that could become a controller; this host is excluded at runtime.
CLUSTER_NODES = ${nodesLiteral}

MOUNT_UNIT_PATH = "/etc/systemd/system/var-lib-linstor.mount"
REACTOR_CONF_PATH = "/etc/drbd-reactor.d/linstor_db.toml"
SATELLITE_DROPIN_DIR = "/etc/systemd/system/linstor-satellite.service.d"
SATELLITE_DROPIN_PATH = SATELLITE_DROPIN_DIR + "/ha.conf"

MOUNT_UNIT = """[Unit]
Description=Filesystem for the LINSTOR controller

[Mount]
What=/dev/drbd/by-res/linstor_db/0
Where=/var/lib/linstor
"""

REACTOR_CONF = """[[promoter]]
[promoter.resources.linstor_db]
start = ["var-lib-linstor.mount", "linstor-controller.service"]
"""

SATELLITE_DROPIN = """[Service]
Environment=LS_KEEP_RES=linstor_db
"""


def run(cmd, check=True, capture=False):
    print("+ " + " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=check, text=True,
                          capture_output=capture)


def out(cmd):
    return subprocess.run(cmd, check=True, text=True,
                          capture_output=True).stdout


def die(msg):
    print("ERROR: " + msg, file=sys.stderr)
    sys.exit(1)


def confirm(prompt):
    reply = input(prompt + " [y/N] ").strip().lower()
    if reply != "y":
        die("aborted by user")


def write_file(path, content):
    print("+ write " + path, flush=True)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)


def preflight():
    if os.geteuid() != 0:
        die("run this script as root")
    for tool in ("linstor", "drbdadm", "drbd-reactor", "mkfs.ext4"):
        if shutil.which(tool) is None:
            die(tool + " not found in PATH — install it first")
    state = subprocess.run(["systemctl", "is-active", "--quiet",
                            "linstor-controller"]).returncode
    if state != 0:
        die("linstor-controller is not active on this node — run the "
            "script on the node currently running the controller")
    # The controller must be reachable before we start moving its DB.
    run(["linstor", "node", "list"], capture=True)
    resources = json.loads(out(["linstor", "--machine-readable",
                                "resource", "list", "-r", RESOURCE]))
    if resources and resources[0]:
        die("resource '" + RESOURCE + "' already exists — this cluster "
            "looks already (partially) HA-configured; resolve manually")
    if os.path.exists(MOUNT_UNIT_PATH):
        die(MOUNT_UNIT_PATH + " already exists — resolve manually")


def rg_exists():
    groups = json.loads(out(["linstor", "--machine-readable",
                             "resource-group", "list"]))
    names = [g.get("name", "") for g in (groups[0] if groups else [])]
    return RESOURCE_GROUP in names


def create_db_resource():
    if rg_exists():
        print("resource group " + RESOURCE_GROUP + " already exists, reusing")
    else:
        run(["linstor", "resource-group", "create",
             "--storage-pool", STORAGE_POOL,
             "--place-count", str(PLACE_COUNT),
             "--diskless-on-remaining", "true",
             RESOURCE_GROUP])
        run(["linstor", "volume-group", "create", RESOURCE_GROUP])
    run(["linstor", "resource-group", "drbd-options",
         "--auto-promote=no",
         "--quorum=majority",
         "--on-suspended-primary-outdated=force-secondary",
         "--on-no-quorum=io-error",
         "--on-no-data-accessible=io-error",
         RESOURCE_GROUP])
    run(["linstor", "resource-group", "spawn-resources",
         RESOURCE_GROUP, RESOURCE, DB_SIZE])


def wait_for_device(path, timeout=60):
    for _ in range(timeout):
        if os.path.exists(path):
            return
        time.sleep(1)
    die(path + " did not appear within " + str(timeout) + "s")


def move_db():
    wait_for_device("/dev/drbd/by-res/linstor_db/0")
    run(["systemctl", "disable", "--now", "linstor-controller"])
    write_file(MOUNT_UNIT_PATH, MOUNT_UNIT)
    run(["systemctl", "daemon-reload"])
    if os.path.exists("/var/lib/linstor.orig"):
        die("/var/lib/linstor.orig already exists — resolve manually")
    os.rename("/var/lib/linstor", "/var/lib/linstor.orig")
    os.mkdir("/var/lib/linstor")
    # LINSTOR >= 1.14.0: keep the mountpoint immutable while unmounted.
    run(["chattr", "+i", "/var/lib/linstor"], check=False)
    run(["drbdadm", "primary", RESOURCE])
    run(["mkfs.ext4", "-b", "4096", "/dev/drbd/by-res/linstor_db/0"])
    run(["systemctl", "start", "var-lib-linstor.mount"])
    run(["cp", "-a", "/var/lib/linstor.orig/.", "/var/lib/linstor/"])


def hand_off_to_reactor():
    write_file(REACTOR_CONF_PATH, REACTOR_CONF)
    write_file(SATELLITE_DROPIN_PATH, SATELLITE_DROPIN)
    run(["systemctl", "daemon-reload"])
    run(["systemctl", "enable", "drbd-reactor"])
    run(["systemctl", "restart", "drbd-reactor"])
    run(["systemctl", "restart", "linstor-satellite"])
    # Reactor promotes linstor_db here (we are primary) and starts the
    # controller; give it a moment before verifying.
    for _ in range(30):
        if subprocess.run(["systemctl", "is-active", "--quiet",
                           "linstor-controller"]).returncode == 0:
            break
        time.sleep(2)
    else:
        die("linstor-controller did not come back under drbd-reactor — "
            "check 'drbd-reactorctl status " + RESOURCE + "'")
    run(["drbd-reactorctl", "status", RESOURCE], check=False)


def print_standby_instructions():
    me = socket.gethostname().split(".")[0]
    standby = [n for n in CLUSTER_NODES if n and n != me]
    if not standby:
        standby = ["<standby-node>"]
    print()
    print("=" * 72)
    print("DONE on this node. Now run the following ON EACH STANDBY NODE")
    print("(" + ", ".join(standby) + ") to finish the HA setup:")
    print("=" * 72)
    print("""
systemctl disable --now linstor-controller

cat <<'EOF' > /etc/systemd/system/var-lib-linstor.mount
""" + MOUNT_UNIT + """EOF

mkdir -p /var/lib/linstor
chattr +i /var/lib/linstor    # LINSTOR >= 1.14.0 only

mkdir -p """ + SATELLITE_DROPIN_DIR + """
cat <<'EOF' > """ + SATELLITE_DROPIN_PATH + """
""" + SATELLITE_DROPIN + """EOF

cat <<'EOF' > """ + REACTOR_CONF_PATH + """
""" + REACTOR_CONF + """EOF

systemctl daemon-reload
systemctl restart linstor-satellite
systemctl enable --now drbd-reactor
systemctl restart drbd-reactor
drbd-reactorctl status """ + RESOURCE + """
""")
    print("Afterwards, point clients and integrations (linstor-client,")
    print("Proxmox, CSI, ...) at the list of all controller IPs.")


def main():
    preflight()
    print("This will move the LINSTOR controller database onto a DRBD")
    print("resource ('" + RESOURCE + "', pool '" + STORAGE_POOL +
          "', " + str(PLACE_COUNT) + " replicas) and hand the controller "
          "over to drbd-reactor.")
    confirm("Continue?")
    create_db_resource()
    move_db()
    hand_off_to_reactor()
    print_standby_instructions()


if __name__ == "__main__":
    main()
`;
};
